#!/bin/bash
# init
echo ".................................."
echo ".................................."
echo ".................................."
echo "...Building marlin for Ender 3...."
echo ".................................."
echo ".................................."
echo ".................................."
git checkout "Ender-3(Bugfix)"
git pull
timeout 60s python3.8 buildroot/share/vscode/auto_build.py build
echo "......................................"
echo "...build complete for ender 3-Bugfix.."
echo "......................................"
cp -f .pio/build/LPC1769/firmware.bin ~/Desktop/Ender3-Bugfix.bin

echo firmware ready on desktop

function pause(){
   read -p "$*"
}
 
pause 'Press [Enter] key to continue...'
